#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"

source "$SCRIPT_DIR/options.sh"
source "$SCRIPT_DIR/ip.sh"

DESTINATION="pi@$SERVER"

echo "Connecting to $DESTINATION..."
ssh $SSH_OPTIONS "$DESTINATION" "$@"
